ANN: supervised

Mô hình FeedForward Network, No FeedBack

Ghép nhiều perceptron hay mạng đa lớp perceptron

In [5]:
import torch
import math


In [7]:

# Kích thước mạng
input_size = 2
hidden_size = 4
output_size = 2

# Hàm kích hoạt
def tanh(x):
    return torch.tanh(x)

def sigmoid(x):
    return 1 / (1 + torch.exp(-x))

# Tạo trọng số và bias ngẫu nhiên
torch.manual_seed(0)  # để tái lập kết quả
W1 = torch.randn(input_size, hidden_size)   # (2, 4)
b1 = torch.randn(hidden_size)               # (4,)
W2 = torch.randn(hidden_size, output_size)  # (4, 2)
b2 = torch.randn(output_size)               # (2,)

# Input mẫu
x = torch.tensor([0.5, -0.2])  # (2,)

# Hidden layer
z1 = torch.matmul(x, W1) + b1     # (4,) = (2,) x (2x4) + (4,)
a1 = tanh(z1)                     # (4,)

# Output layer
z2 = torch.matmul(a1, W2) + b2    # (2,) = (4,) x (4x2) + (2,)
a2 = sigmoid(z2)                  # (2,)

# In kết quả từng bước
print("Input:", x)
print("Z1 (xW1 + b1):", z1)
print("A1 (tanh):", a1)
print("Z2 (a1W2 + b2):", z2)
print("A2 (sigmoid):", a2)


Input: tensor([ 0.5000, -0.2000])
Z1 (xW1 + b1): tensor([ 0.2681, -0.2703, -1.7667,  0.2986])
A1 (tanh): tensor([ 0.2619, -0.2639, -0.9432,  0.2901])
Z2 (a1W2 + b2): tensor([0.7042, 0.9227])
A2 (sigmoid): tensor([0.6691, 0.7156])


In [4]:

# Kích thước mạng
input_size = 2
hidden_size = 4
output_size = 2

# Tạo trọng số và bias ngẫu nhiên
torch.manual_seed(0)  # để tái lập kết quả
W1 = torch.randn(input_size, hidden_size)   # (2, 4)
b1 = torch.randn(hidden_size)               # (4,)
W2 = torch.randn(hidden_size, output_size)  # (4, 2)
b2 = torch.randn(output_size)               # (2,)

# Input mẫu
x = torch.tensor([0.5, -0.2])  # (2,)

# Tính toán forward pass

# Hidden layer
z1 = torch.matmul(x, W1) + b1     # (4,) = (2,) x (2x4) + (4,)
a1 = tanh(z1)                     # (4,)

# Output layer
z2 = torch.matmul(a1, W2) + b2    # (2,) = (4,) x (4x2) + (2,)
a2 = sigmoid(z2)                  # (2,)

# In kết quả từng bước
print("Input:", x)
print("Z1 (xW1 + b1):", z1)
print("A1 (tanh):", a1)
print("Z2 (a1W2 + b2):", z2)
print("A2 (sigmoid):", a2)


Input: tensor([ 0.5000, -0.2000])
Z1 (xW1 + b1): tensor([ 0.2681, -0.2703, -1.7667,  0.2986])
A1 (tanh): tensor([ 0.2619, -0.2639, -0.9432,  0.2901])
Z2 (a1W2 + b2): tensor([0.7042, 0.9227])
A2 (sigmoid): tensor([0.6691, 0.7156])


C:\Users\OS\AppData\Local\Temp\ipykernel_17708\1625773255.py:11: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  return (np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))
C:\Users\OS\AppData\Local\Temp\ipykernel_17708\1625773255.py:3: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  return 1/(1+np.exp(-x))


[1.06466696 2.15480078]
[[1 1 2]
 [1 2 0]]
[1 1 1]
[4 3]
[4 3]
